# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BigmileCli < Formula
  desc ""
  homepage "https:/bigmile.eu"
  version "0.5"

  on_macos do
    url "https://github.com/mikkurogue/bigmile-cli/releases/download/v0.5/bigmile-cli_0.5_darwin_all.tar.gz"
    sha256 "2a5201b84ba3a6eff3de378b4324dbfdde5eeb15af9ffe686dc84cd2c9433354"

    def install
      bin.install "bigmile-cli"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mikkurogue/bigmile-cli/releases/download/v0.5/bigmile-cli_0.5_linux_amd64.tar.gz"
        sha256 "cff9702674943b06d786537202adabc4c7fb4f08af3c243f2bd8f27ea4aa9831"

        def install
          bin.install "bigmile-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mikkurogue/bigmile-cli/releases/download/v0.5/bigmile-cli_0.5_linux_arm64.tar.gz"
        sha256 "f3c4f182a19028bbd8f82ccd9da1c77b696a65ed95c295065c18afbd605f6879"

        def install
          bin.install "bigmile-cli"
        end
      end
    end
  end
end
