# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategy"
class BigmileCli < Formula
  desc ""
  homepage "https:/bigmile.eu"
  version "0.8"

  on_macos do
    url "https://github.com/mikkurogue/bigmile-cli/releases/download/v0.8/bigmile-cli_0.8_darwin_all.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "304aeba9499a7092076a1e9c661b730ecdb453933108a6bdf6c67e1dab93c776"

    def install
      bin.install "bigmile-cli"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mikkurogue/bigmile-cli/releases/download/v0.8/bigmile-cli_0.8_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "37f0933b159f86c648194dcbd42f5a4ea55d48102311e99432d0c937b3e212fe"

        def install
          bin.install "bigmile-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mikkurogue/bigmile-cli/releases/download/v0.8/bigmile-cli_0.8_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "38dfdc77c8bd99bdb40690b0131aeb72a3cf1774cd74d7d7b67e493ac1b31835"

        def install
          bin.install "bigmile-cli"
        end
      end
    end
  end
end
