# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategy"
class BigmileCli < Formula
  desc ""
  homepage "https:/bigmile.eu"
  version "1.0"

  on_macos do
    url "https://github.com/mikkurogue/bigmile-cli/releases/download/1.0/bigmile-cli_1.0_darwin_all.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "dd504ac820b3504d20ae05e89c1898175c25406e7993bc180cf4eccb37f9268d"

    def install
      bin.install "bigmile-cli"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mikkurogue/bigmile-cli/releases/download/1.0/bigmile-cli_1.0_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "d2ac9c3b56fd0c7eb66dbc500c73e68d6be7173a247decaa54f8c61ae58178ef"

        def install
          bin.install "bigmile-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mikkurogue/bigmile-cli/releases/download/1.0/bigmile-cli_1.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "b9cf10b6001d7822f7839c584dd364ce6689d01009c1ed22269da95dd3244e96"

        def install
          bin.install "bigmile-cli"
        end
      end
    end
  end
end
