# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategy"
class Dagger < Formula
  desc ""
  homepage "https://github.com/mikkurogue/dagger-cli"
  version "1.1"

  on_macos do
    url "https://github.com/mikkurogue/Dagger-CLI/releases/download/1.1/Dagger-CLI_1.1_darwin_all.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "d916b17d1a46db24f6ff389bc351223b7ac8d97d871f5e790ead85ff4ffd4c6b"

    def install
      bin.install "Dagger-CLI"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mikkurogue/Dagger-CLI/releases/download/1.1/Dagger-CLI_1.1_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "f1245c621c6cac02cbfbdba662cc8fecd598f89c0557dd2a1d64ebc6ee850e5f"

        def install
          bin.install "dgr"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mikkurogue/Dagger-CLI/releases/download/1.1/Dagger-CLI_1.1_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "9fe54aa78f1bda3f8d3ce47bbae768836016e02276fc13e6edba5f125fab9260"

        def install
          bin.install "dgr"
        end
      end
    end
  end
end
