# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dagger < Formula
  desc ""
  homepage "https://github.com/mikkurogue/dagger-cli"
  version "1.1.10"

  on_macos do
    url "https://github.com/mikkurogue/dagger-cli/releases/download/1.1.10/dagger-cli_1.1.10_darwin_all.tar.gz"
    sha256 "6b839bd10569cd9a1df7b26a35ea00bc02b3d9d51620bea9b362358954e2760b"

    def install
      bin.install "dagger-cli"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mikkurogue/dagger-cli/releases/download/1.1.10/dagger-cli_1.1.10_linux_amd64.tar.gz"
        sha256 "af97cbd22ac02a52e3e856531620266316e8fe538cc69f8e93dadd32ab8c633d"

        def install
          bin.install "dagger"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mikkurogue/dagger-cli/releases/download/1.1.10/dagger-cli_1.1.10_linux_arm64.tar.gz"
        sha256 "a45caa5dc8be89b8f962ee6d402e9757b885947faaa5711c4a40df8948c0dba6"

        def install
          bin.install "dagger"
        end
      end
    end
  end
end
