# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dagger < Formula
  desc ""
  homepage "https://github.com/mikkurogue/dagger-cli"
  version "1.1.1"

  on_macos do
    url "https://github.com/mikkurogue/Dagger-CLI/releases/download/1.1.1/Dagger-CLI_1.1.1_darwin_all.tar.gz"
    sha256 "d0d8057aaf45d766c3e7d4aaccdf8c9602b76d5a2279e50961c75332722e2a58"

    def install
      bin.install "Dagger-CLI"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mikkurogue/Dagger-CLI/releases/download/1.1.1/Dagger-CLI_1.1.1_linux_amd64.tar.gz"
        sha256 "3d2ffa2e614d193058f30f703e722314800bd34aa4d8fbdef72e6a9a1310ca8c"

        def install
          bin.install "dgr"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mikkurogue/Dagger-CLI/releases/download/1.1.1/Dagger-CLI_1.1.1_linux_arm64.tar.gz"
        sha256 "fb59dd35e5bda8f2678abe124389c09eeb4a3080767ce9889a986970dba63118"

        def install
          bin.install "dgr"
        end
      end
    end
  end
end
